package intro

import (
	"crypto/sha1"
	"encoding/binary"
	"fmt"
	"math/rand"
	"strings"

	"intro-go/internal/db"
)

// ThinkingMessage is the SSE "thinking" payload shown while the intro is built.
func ThinkingMessage() string {
	return "🤔 Generating your intro…"
}

// Generate composes a 3-5 sentence intro from the user (and optionally their
// GitHub profile). Output is deterministic for a given user.Name so a refresh
// does not flip the wording. It is pure and does no I/O.
func Generate(u *db.User, gh *db.GithubProfile) string {
	if u == nil {
		return ""
	}

	rng := rand.New(rand.NewSource(nameHash(u.Name)))
	name := displayName(u)

	var sentences []string

	if gh != nil {
		sentences = append(sentences, pick(rng, githubOpeners(name, gh.Username)))
		if gh.Bio.Valid && gh.Bio.String != "" {
			sentences = append(sentences, pick(rng, bioLines(gh.Username, gh.Bio.String)))
		} else {
			sentences = append(sentences, pick(rng, noBioLines(gh.Username)))
		}
		sentences = append(sentences, pick(rng, repoLines(gh.Username, gh.PublicRepos)))
	} else {
		sentences = append(sentences, pick(rng, userOpeners(name)))
		if u.Email != "" {
			sentences = append(sentences, pick(rng, emailLines(name, u.Email)))
		}
		sentences = append(sentences, pick(rng, userExtras(name)))
	}

	// Closing line always notes the generation source.
	sentences = append(sentences, pick(rng, closingLines()))

	return strings.Join(sentences, " ")
}

// Words splits an intro on whitespace, dropping empty tokens (one SSE event
// per emitted word).
func Words(intro string) []string {
	intro = strings.TrimSpace(intro)
	if intro == "" {
		return nil
	}
	return strings.Fields(intro)
}

func displayName(u *db.User) string {
	if u.Name != "" {
		return u.Name
	}
	if u.Email != "" {
		return u.Email
	}
	return "this user"
}

func nameHash(name string) int64 {
	sum := sha1.Sum([]byte(name))
	return int64(binary.BigEndian.Uint64(sum[:8]))
}

func pick(rng *rand.Rand, opts []string) string {
	return opts[rng.Intn(len(opts))]
}

func githubOpeners(name, username string) []string {
	return []string{
		fmt.Sprintf("Meet %s, who builds in the open on GitHub as @%s.", name, username),
		fmt.Sprintf("This is %s, best known on GitHub by the handle @%s.", name, username),
		fmt.Sprintf("Say hello to %s, the person behind the @%s account.", name, username),
		fmt.Sprintf("%s ships code publicly under the @%s handle.", name, username),
	}
}

func bioLines(username, bio string) []string {
	return []string{
		fmt.Sprintf("Their profile bio reads: \"%s\".", bio),
		fmt.Sprintf("According to GitHub, @%s describes themselves as \"%s\".", username, bio),
		fmt.Sprintf("In their own words: \"%s\".", bio),
	}
}

func noBioLines(username string) []string {
	return []string{
		fmt.Sprintf("@%s keeps their bio blank for now, letting the code speak for itself.", username),
		fmt.Sprintf("They haven't written a bio on @%s yet, so the repositories tell the story instead.", username),
	}
}

func repoLines(username string, repos int32) []string {
	return []string{
		fmt.Sprintf("@%s currently maintains %d public repositories across a range of projects.", username, repos),
		fmt.Sprintf("With %d public repositories, @%s has shipped plenty of open-source work.", repos, username),
		fmt.Sprintf("Their %d public repositories give a window into what @%s builds day to day.", repos, username),
	}
}

func userOpeners(name string) []string {
	return []string{
		fmt.Sprintf("Meet %s, a member of the community.", name),
		fmt.Sprintf("This is %s, who recently joined the platform.", name),
		fmt.Sprintf("Say hello to %s.", name),
	}
}

func emailLines(name, email string) []string {
	return []string{
		fmt.Sprintf("You can reach %s at %s.", name, email),
		fmt.Sprintf("%s can be contacted via %s.", name, email),
	}
}

func userExtras(name string) []string {
	return []string{
		fmt.Sprintf("%s is still setting up their profile, so there's more to come.", name),
		fmt.Sprintf("There isn't much public detail on %s yet, but watch this space.", name),
	}
}

func closingLines() []string {
	return []string{
		"This introduction was generated by a Go microservice running on ECS Fargate.",
		"Powered by a Go microservice deployed to ECS Fargate.",
		"Generated on the fly by a Go microservice hosted on ECS Fargate.",
	}
}
